### PR TITLE
Add FixedRotationOrigin option

### PR DESCRIPTION
**Pull request by rusefillc**
(cherry picked from commit 1ad1952274734f0968b8f3e9a48bec640be7c2a7)

### CODE REVIEW

**Comment by rusefillc** [comment]
Hello @frank-f :)

@andreika-git and myself are huge fans of gerbmerge, we use it for KiCAD 6

Within the whole mess of zillions of gerbmerge forks yours seems like the most alive. It also looks like we've made the mistake of not starting from your fork when we have started our 2021 batch of changes. Our small 2017 changes you have :)

Mostly trying to start the conversation and attempting for find at least something we can PR into your fork. With this speicific small change here to be honest so far I do not understand why is it a merge conflict.

**Comment by frank-f** [comment]
Not sure, why Git did not add your commit to the history, but I can tell you the reason for the conflict.

In order to get things a litte more consistent, I went through the project and made indentations and lineendings consistent. Github does not show this in the UI, but the config file was one of the files with strange lineendings so the entire file was changed during my cleanup. This seems to confuse automatic merging.

**Comment by rusefillc** [comment]
Oohhhhhhhhhhhhh I see

While clean code formatting is tempting it would also be a huge impediment for anyone trying to deal with all the commits in all the forks around.

I will now create a new version of the same commit by just re-applying the change manually.

**Comment by rusefillc** [comment]
Oh just realized that you've pushed this change already, THANK YOU!

**Comment by frank-f** [comment]
> While clean code formatting is tempting it would also be a huge impediment for anyone trying to deal with all the commits in all the forks around.

Since the development on gerbmerge seemed pretty dead, I never intended to submit my changes to any upstream repo.

Anyhow, I went through the commits in [rusefi/gerbmerge#rusefi-tests](https://github.com/rusefi/gerbmerge/tree/rusefi-tests) and cherry picked them into my fork. I used this command, which works well with my formatting changes:

`git cherry-pick <commit-id> --strategy=recursive --strategy-option=renormalize --strategy-option=ignore-space-at-eol`

**Comment by rusefillc** [comment]
oh, today I've learned a new trick! thank you for the progress

@andreika-git FYI

let me respond on #3 that one seems more relevant

**Pull request closed without merging**
